### ISSUE TITLE
Broken menu navigation

### ISSUE THREAD

**Issue by growfio** [wpexplorer/earth-wordpress-theme#5]
Hey there,

After doing extensive troubleshooting and testing, the newest version of WordPress is not compatible with the menu in this theme. On desktop, the dropdown menu functionality doesn't work / the submenu options don't appear. And on mobile, the mobile menu doesn't show at all.

Website: https://bundlebabyshop.com/

How soon do you think a fix can be pushed out?

Thanks

**Comment by wpexplorer** [comment]
@growfio - Hey there, the fix was already released a while back. See here: https://github.com/wpexplorer/earth-wordpress-theme/releases/tag/4.5

**Comment by growfio** [comment]
Version 4.5 completely breaks the website though, and then it disregards the previous child theme. The child theme can't even be activated with 4.5

**Comment by wpexplorer** [comment]
@growfio - Version 4.5 has been tested without issues.

The only thing I can think of is that you are downloading the file from github and uploading it with the Github zip name (it's not possible to change the name here on github). So when you download the theme it will be named "earth-wordpress-theme-4.5.zip" make sure to extract, rename to "earth", re-zip and upload to WordPress.

**Comment by growfio** [comment]
Renaming the theme and uploading it causes the following errors and breaks the site:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/bundlebabyshop37/public_html/wp-content/plugins/revslider/includes/operations.class.php on line 2734

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/bundlebabyshop37/public_html/wp-content/plugins/revslider/includes/operations.class.php on line 2738

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/bundlebabyshop37/public_html/wp-content/plugins/revslider/includes/output.class.php on line 3679

Parse error: syntax error, unexpected '=' in /home/bundlebabyshop37/public_html/wp-content/themes/twentytwentyone/functions.php on line 633

There has been a critical error on this website. Please check your site admin email inbox for instructions.

**Comment by wpexplorer** [comment]
Hi,

If you read the errors you can see they are coming from Slider Revolution so this would have nothing to do with the theme update itself. Those errors would have already been present since updating the theme wouldn't modify anything to do with the slider. So if you only see the errors after updating the theme that wouldn't make much sense, hmm...

The last error is referring to the "twentytwentyone" theme which would imply you have the "twentytwentyone" theme activated and not the Earth theme.

I re-downloaded and tested and confirmed it should work as intended. I recorded a video for you so. you can see: https://a.cl.ly/geuoey5Z

- AJ

**Comment by growfio** [comment]
Thank you so much. Made progress and now the menu is fixed. I'll replace the slider in the meantime to static image since that'll remove the slider errors.

Speaking of errors, what does this mean? It's showing on the top of the website. How to remove? Warning: Invalid argument supplied for foreach() in /home/bundlebabyshop37/public_html/wp-content/themes/earth/inc/theme-panel/classes/class.options_machine.php on line 178

**Comment by wpexplorer** [comment]
Hi,

It's hard to know what this error is without actually logging into the site via FTP. Basically it suggest that there is a setting in the theme panel that is array based but has an incorrect value for the array. It could very well be an option in the theme panel that has a value saved that's incorrect such as a broken image. If you reset the theme panel, I'm guessing the error would go away, of course then you may have to re-do your settings (maybe you can save the settings, reset and then import them again and see if that works).

I can't actually recreate the error on my end, the theme shouldn't have any errors, so it's most likely, like I said a theme panel setting that has been saved with an incorrect value somehow. Perhaps the error comes from updating from an old version of the theme since the theme panel in Earth uses a 3rd party framework it has received various updates over the years so perhaps the way a specific field was saved/sanitized has changed causing the debug warning (this is technically a warning so it shouldn't really break anything on the site - you could technically disable WP_Debug and ignore it - in fact for security it's generally recommended to keep WP_Debug disabled on. your WP site). My newer themes like [Total](https://total.wpexplorer.com/) actually use the WordPress Customizer instead which is built-into WordPress, but because the earth theme was basically making negative income having it available for sale I can't continue it's development. I have actually been deprecating all my old premium themes to focus my time fully on the Total theme so that I can instead have one really good theme that I can fully maintain and support for years to come, instead of breaking my time up into multiple projects. Maybe one day you would consider switching over ;)

- AJ

**Comment by growfio** [comment]
Yeah it's weird because resetting the theme options and clearing the cache didn't do anything to hide the error. define('WP_DEBUG', false); is defined in the wp-config file, but it's still showing on the backend.

I'm aware you're newest theme is far more up-to-date and supported, but this site here is a client site and they're not looking to redesign anything any time soon. Once they reach that point I can consider switching for them, but for now they're wanting to stick with the Earth theme even though they know it's not getting develop updates. Thanks all for your help

**Comment by wpexplorer** [comment]
Generally speaking I don't really support these old themes, but I don't get many questions so I don't really mind. If you wanted you can send me temp WP and FTP logins to wpexplorer [at] gmail [dot] com so I can take a look for you and see if we can get the notice removed. Best would be to email me, I will reply back and then you can send me the logins. This way there is no potential of accidentally sending credentials to the incorrect place.

- AJ

**Comment by growfio** [comment]
You're awesome, thanks so much. Just sent you off an email titled "Earth theme". Please let me know if you have any questions. Thanks!

**Comment by wpexplorer** [comment]
@growfio - Got the email. I will have a look either tonight or first thing tomorrow. I appreciate your patience.

ps: I haven't clicked the link yet, just incase. Will do once I can sit down and focus on this.

**Comment by wpexplorer** [comment]
Debug errors fixed by https://github.com/wpexplorer/earth-wordpress-theme/commit/9710cb2f23edba495f953a1e1723f658c5c80039
